name: Azure Container Apps Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure Storage Account
        run: |
          az storage account create \
            --name mystorageac18324count \
            --resource-group datta-test \
            --location centralindia \
            --sku Standard_LRS

      - name: Create Azure File Share
        run: |
          az storage share create \
            --name myfileshare \
            --account-name mystorageac18324count

      - name: Get Storage Account Key
        id: get_storage_key
        run: |
          storage_key=$(az storage account keys list --resource-group datta-test --account-name mystorageac18324count --query '[0].value' --output tsv)
          echo "::set-output name=storage_key::$storage_key"

      - name: Build and deploy Container App
        run: |
          az containerapp create \
            --name my-container-app \
            --resource-group datta-test \
            --environment my-environment \
            --image jenkins/jenkins:lts-jdk17 \
            --env-vars AZURE_STORAGE_ACCOUNT=mystorageaccount AZURE_STORAGE_KEY=${{ steps.get_storage_key.outputs.storage_key }} \
            --volume-mount name=myazurefile storage-account-name=mystorageac18324count storage-account-key=${{ steps.get_storage_key.outputs.storage_key }} share-name=myfileshare mount-path=/var/jenkins_home
